
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed FixedCont;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Button buttonResult;

	private global::Gtk.Button buttonPlus;

	private global::Gtk.Button buttonMinus;

	private global::Gtk.Button buttonMultiply;

	private global::Gtk.Button buttonDivision;

	private global::Gtk.Label calcLabel;

	private global::Gtk.Button button15;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 240;
		this.HeightRequest = 270;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 270;
		this.DefaultHeight = 240;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.FixedCont = new global::Gtk.Fixed();
		this.FixedCont.Name = "FixedCont";
		this.FixedCont.HasWindow = false;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 50;
		this.button1.HeightRequest = 50;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.FixedCont.Add(this.button1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button1]));
		w1.X = 20;
		w1.Y = 50;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 50;
		this.button2.HeightRequest = 50;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.FixedCont.Add(this.button2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button2]));
		w2.X = 70;
		w2.Y = 50;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.WidthRequest = 50;
		this.button3.HeightRequest = 50;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.FixedCont.Add(this.button3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button3]));
		w3.X = 120;
		w3.Y = 50;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.WidthRequest = 50;
		this.button4.HeightRequest = 50;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.FixedCont.Add(this.button4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button4]));
		w4.X = 20;
		w4.Y = 100;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 50;
		this.button5.HeightRequest = 50;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.FixedCont.Add(this.button5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button5]));
		w5.X = 70;
		w5.Y = 100;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 50;
		this.button6.HeightRequest = 50;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.FixedCont.Add(this.button6);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button6]));
		w6.X = 120;
		w6.Y = 100;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button7 = new global::Gtk.Button();
		this.button7.WidthRequest = 50;
		this.button7.HeightRequest = 50;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.FixedCont.Add(this.button7);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button7]));
		w7.X = 20;
		w7.Y = 150;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button8 = new global::Gtk.Button();
		this.button8.WidthRequest = 50;
		this.button8.HeightRequest = 50;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.FixedCont.Add(this.button8);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button8]));
		w8.X = 70;
		w8.Y = 150;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button9 = new global::Gtk.Button();
		this.button9.WidthRequest = 50;
		this.button9.HeightRequest = 50;
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.FixedCont.Add(this.button9);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button9]));
		w9.X = 120;
		w9.Y = 150;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.buttonResult = new global::Gtk.Button();
		this.buttonResult.WidthRequest = 100;
		this.buttonResult.HeightRequest = 50;
		this.buttonResult.CanFocus = true;
		this.buttonResult.Name = "buttonResult";
		this.buttonResult.UseUnderline = true;
		this.buttonResult.Label = global::Mono.Unix.Catalog.GetString("=");
		this.FixedCont.Add(this.buttonResult);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.buttonResult]));
		w10.X = 20;
		w10.Y = 200;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.buttonPlus = new global::Gtk.Button();
		this.buttonPlus.WidthRequest = 50;
		this.buttonPlus.HeightRequest = 50;
		this.buttonPlus.CanFocus = true;
		this.buttonPlus.Name = "buttonPlus";
		this.buttonPlus.UseUnderline = true;
		this.buttonPlus.Label = global::Mono.Unix.Catalog.GetString("+");
		this.FixedCont.Add(this.buttonPlus);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.buttonPlus]));
		w11.X = 170;
		w11.Y = 50;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.buttonMinus = new global::Gtk.Button();
		this.buttonMinus.WidthRequest = 50;
		this.buttonMinus.HeightRequest = 50;
		this.buttonMinus.CanFocus = true;
		this.buttonMinus.Name = "buttonMinus";
		this.buttonMinus.UseUnderline = true;
		this.buttonMinus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.FixedCont.Add(this.buttonMinus);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.buttonMinus]));
		w12.X = 170;
		w12.Y = 100;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.buttonMultiply = new global::Gtk.Button();
		this.buttonMultiply.WidthRequest = 50;
		this.buttonMultiply.HeightRequest = 50;
		this.buttonMultiply.CanFocus = true;
		this.buttonMultiply.Name = "buttonMultiply";
		this.buttonMultiply.UseUnderline = true;
		this.buttonMultiply.Label = global::Mono.Unix.Catalog.GetString("*");
		this.FixedCont.Add(this.buttonMultiply);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.buttonMultiply]));
		w13.X = 170;
		w13.Y = 150;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.buttonDivision = new global::Gtk.Button();
		this.buttonDivision.WidthRequest = 50;
		this.buttonDivision.HeightRequest = 50;
		this.buttonDivision.CanFocus = true;
		this.buttonDivision.Name = "buttonDivision";
		this.buttonDivision.UseUnderline = true;
		this.buttonDivision.Label = global::Mono.Unix.Catalog.GetString("/");
		this.FixedCont.Add(this.buttonDivision);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.buttonDivision]));
		w14.X = 170;
		w14.Y = 200;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.calcLabel = new global::Gtk.Label();
		this.calcLabel.WidthRequest = 200;
		this.calcLabel.HeightRequest = 40;
		this.calcLabel.Name = "calcLabel";
		this.calcLabel.Xalign = 1F;
		this.calcLabel.Yalign = 1F;
		this.FixedCont.Add(this.calcLabel);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.calcLabel]));
		w15.X = 20;
		w15.Y = 10;
		// Container child FixedCont.Gtk.Fixed+FixedChild
		this.button15 = new global::Gtk.Button();
		this.button15.WidthRequest = 50;
		this.button15.HeightRequest = 50;
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("0");
		this.FixedCont.Add(this.button15);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.FixedCont[this.button15]));
		w16.X = 120;
		w16.Y = 200;
		this.Add(this.FixedCont);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button2.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button3.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button4.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button5.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button6.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button7.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button8.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.button9.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
		this.buttonResult.Clicked += new global::System.EventHandler(this.ButtonResultClick);
		this.buttonPlus.Clicked += new global::System.EventHandler(this.ButtonOperatorClick);
		this.buttonMinus.Clicked += new global::System.EventHandler(this.ButtonOperatorClick);
		this.buttonMultiply.Clicked += new global::System.EventHandler(this.ButtonOperatorClick);
		this.buttonDivision.Clicked += new global::System.EventHandler(this.ButtonOperatorClick);
		this.button15.Clicked += new global::System.EventHandler(this.ButtonNumberClick);
	}
}
